spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.118.55.237:3306/db_laboratory?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 526500siji
server:
  port: 9000

logging:
  level:
    root: info
    com.miku.lab.dao: debug
