spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.118.55.237:3306/db_laboratory?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 526500siji
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
server:
  port: 9000
## 文件访问路径
file:
  common:
    ## windows系统下访问路径
    uploadWindow: C:\pictureUpload\project\
    ## windows系统下访问路径
    uploadLinux: /root/pictureUpload/project/
logging:
  level:
    root: info
    com.miku.lab.dao: debug
