spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_laboratory?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 526500siji
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
server:
  port: 9000

logging:
  level:
    root: info
    com.miku.lab.dao: debug
